### ISSUE TITLE
how to transfer question to GraphQ IR

### ISSUE THREAD

**Issue by mug2mag** [Flitternie/GraphQ_Trans#10]
How to interpret a question to its corresponding GraphQ IR? I did find the api in `graphq_trans`. Would you please mind showing me the code?

like you the example in the official website:
transfer the question `Which movie is shorter, Immortals or North?` to `which one has the smallest <A> duration </A> among <ES><E> Immortals </E> or <E> North </E></ES>`

**Comment by Flitternie** [comment]
To clarify, this repository (**Flitternie/GraphQ_Trans**) contains the implementation for our source-to-source compiler that **converts between GraphQ IR and different graph query languages**. There is no API in `graphq_trans` package that can convert natural language into GraphQ IR.

If I understand it correctly, you should have more interest in the implementation of our neural semantic parser that **converts natural language questions into GraphQ IR** or other logical forms. If so, please refer to the code and documentation in [another repository](https://github.com/Flitternie/GraphQ_IR) (**Flitternie/GraphQ_IR**). Yet during your reproduction of that repository, you still need to install the `graphq_trans` package as an environmental prerequisite.

**Comment by Flitternie** [comment]
@mug2mag This issue will now close. You may reopen this issue if you have further questions.
