### ISSUE TITLE
Does support chinese language ?

### ISSUE THREAD

**Issue by feng-1985** [Flitternie/GraphQ_Trans#11]
such as translate the following sparql query to ir:
select ?x where { ?x <职业> <导演>. ?x <国籍> <中华人民共和国>. ?x <主要成就> "威尼斯国际电影节金狮奖". }

**Comment by Flitternie** [comment]
GraphQ_Trans can work well if the syntax of your query conforms to our style requirements ([link](https://github.com/Flitternie/GraphQ_Trans/#style-requirement)). For example, in your example, if `< 导演 >` and `< 中华人民共和国 >` are entities, and  `"威尼斯国际电影节金狮奖"` is an attribute, then the style-conforming SPARQL should look like:
```
SELECT ?e_1 WHERE {?e_1 <职业> ?e_2 . ?e_2 <pred:name> "导演" . ?e_1 <国籍> ?e_3 . ?e_3 <pred:name> "中华人民共和国" .  ?e_1 <主要成就> ?pv . ?pv <pred:value> "威尼斯国际电影节金狮奖" . }

**Comment by Flitternie** [comment]
@feng-1985 This issue will now close. You may reopen this issue if you have further questions.
