### ISSUE TITLE
Error when translating from graphq to the overnight format

### ISSUE THREAD

**Issue by leezythu** [Flitternie/GraphQ_Trans#9]
Hi, It is a great tool! But I encountered some problems when translating from the graphq format to the overnight format. Specifically, I run:
```
from graphq_trans.sparql.translator import Translator as SparqlTranslator
from graphq_trans.ir.translator import Translator as IRTranslator

sparql_translator = SparqlTranslator() 
ir_translator = IRTranslator() 

sparql_query = 'SELECT DISTINCT ?e WHERE { ?e <pred:instance_of> ?c . ?c <pred:name> "human" } '

ir = sparql_translator.to_ir(sparql_query) 
dcs_query = ir_translator.to_overnight(ir) 
print(dcs_query) 
```
It returns an error.
I tried to debug it and found the problem is that `tree = self.parse(input)` in the `to_overnight()` function returns an empty list. I printed the `tree` and the result is `tree: []`.
My environment is:
* python 3.8.0 (I also tried 3.7)
* antlr4-python3-runtime 4.9.2
* antlr4 4.9
Do you have any idea to solve this problem? I would appreciate it if you can provide some suggestions~

**Comment by Flitternie** [comment]
Thanks for raising this issue.

In your example, since it is not a query grounded on Overnight's domain grammar (as in `./overnight/grammar/`), please create your `ir_translator` in this way: 
`ir_translator = IRTranslator(ungrounded=True)`

Please let me know if this fixes the bug or not.

**Comment by Flitternie** [comment]
`tree` should be a `RootContext` object, and `print(tree)` does expect to return `[]`. 
If you wish to print the string form of the parse tree, it should be `print(tree.toStringTree(recog=parser))`.
You may refer to the respective `parser.py` for details.

**Comment by leezythu** [comment]
Thank you for your patience and help! It does helps me a lot.
